### ISSUE TITLE
Support Azure Pipelines

### ISSUE THREAD

**Issue by kimwalisch** [kimwalisch/primesieve-python#36]
@brl0 I have now added you as an administrator to https://dev.azure.com/kimwalisch/primesieve-python. And I was able to launch the first successful build of primesieve-python :-)

Up until now I have always manually uploaded build artifacts (primesieve-python packages) to pypi using the twine command-line tool. I think this is also (using twine) how we could upload build artifacts from Azure Pipelines to pypi. For this reason I have set up a service connection named ```upload-primesieve-to-pypi``` which contains the credentials to upload to https://pypi.org/project/primesieve.

So now we need to figure out how to use twine and the service connection that I have created to uploaded the build artifacts. Could you help with this? Here is some documentation https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/twine-authenticate?view=azure-devops that explains how to do it...

**Comment by brl0** [comment]
Will do, happy to help.

**Comment by brl0** [comment]
I don't seem to have sufficient permissions in Azure.

**Comment by kimwalisch** [comment]
I have done some minor modifications to your permissions.

Can you sign into: https://dev.azure.com/kimwalisch/primesieve-python?

Can you access the project settings https://dev.azure.com/kimwalisch/primesieve-python/_settings?

**Comment by brl0** [comment]
The first link opens fine, the second gives me a permission denied error.

**Comment by brl0** [comment]
In the meantime, I am working on using twine to upload to TestPyPI from my repo.  Once that works, it will be easy to update or even simply provide quick instructions to get the upload working.

**Comment by kimwalisch** [comment]
I think I have fixed the permission issues now. Each azure project seems to have 8 predefined permission groups and when a new user or administrator is added he is not automatically added to all permissions groups...

Can you try again try if you have full access now?

**Comment by brl0** [comment]
Can you also add me as a maintainer on https://test.pypi.org/project/primesieve/ ?
I want to test the upload process first.

Here is what I am using:

```
- script: |
    python -m pip install -U wheel
    python setup.py bdist_wheel
  displayName: 'Build'

- script: |
    python -m pip install -U twine
    python -m twine upload --skip-existing --verbose --repository-url https://test.pypi.org/legacy -u __token__ -p $(test_pypi) dist/*
  displayName: 'Upload'
```

The only problem I am running into is lack of permission to the primesieve project on test.pypi.org.  I suspect the upload would work correctly to the real pypi, but I would prefer to test first.

**Comment by brl0** [comment]
I still don't seem to have access rights on Azure.  I cannot edit the pipeline or clone it to make a new one.

**Comment by brl0** [comment]
Access to TestPyPI is working and has allowed me to advance far enough to slam into new walls.

Linux builds are not proper manylinux1 builds, so I have to figure out how to do that.

Windows uploads throws the following error:
`The description failed to render in the default format of reStructuredText.`

On the bright side, the Mac builds seemed to work without issue.

At least we're making some progress.

**Comment by kimwalisch** [comment]
> I still don't seem to have access rights on Azure. I cannot edit the pipeline or clone it to make a new one.

I have created myself a second GitHub user and I am able to reproduce your error. It is a fu.... permission nightmare, even though I have granted my second GitHub user admin permissions in 20 different places the second user cannot access e.g. the project settings.

I will try to ask for help in a forum...

**Comment by kimwalisch** [comment]
Here is the link to my question on the Azure forum: 

https://developercommunity.visualstudio.com/content/problem/853100/how-to-add-another-admin-user-to-project-on-httpsd.html

**Comment by kimwalisch** [comment]
I think it works now! I have found yet another place where I can add admins...

**Comment by brl0** [comment]
I think I have the builds and uploads working.

The problem was the Linux builds, which have to be built by a special docker image to produce the manylinux builds correctly.  See [PEP 513](https://www.python.org/dev/peps/pep-0513/).

I found a tool, [cibuildwheel](https://cibuildwheel.readthedocs.io/), that builds wheels correctly on all platforms.  

I will try to get this working on the production pipeline next.

**Comment by brl0** [comment]
Unfortunately, still not able to do anything other than view the pipeline.  I signed out and back in, still no luck.

**Comment by kimwalisch** [comment]
> Unfortunately, still not able to do anything other than view the pipeline. I signed out and back in, still no luck.

My second GitHub user has full access, I will investigate...

**Comment by kimwalisch** [comment]
It definitely works for my second GitHub user. I have created a **primesieve-python Team** group with admin rights and as soon as I add my second user to that group he has full access. I have now removed your old user and then added it back in to that group. 

My second GitHub user can access the project settings, can you too?

https://dev.azure.com/kimwalisch/primesieve-python/_settings

**Comment by brl0** [comment]
Awesome, it works now!
Sorry for the delay in getting back to this.  
Hopefully now everything is lined up to get this going.

**Comment by brl0** [comment]
Everything appears to be in good working order now.  The builds all run and upload to test.pypi.org.
Do you have any questions or concerns before I make the change to upload to the real PyPI?

**Comment by kimwalisch** [comment]
> Everything appears to be in good working order now. The builds all run and upload to test.pypi.org.
Do you have any questions or concerns before I make the change to upload to the real PyPI?

Good work!

I have had a look at the download files at https://test.pypi.org/project/primesieve/#files and I realized that the ```primesieve-2.0.1.tar.gz``` source archive is missing. I think we need to upload that as well for operating systems and/or CPUs for which we do not have binary packages!?

I see that we have binary packages for Python-3.6 or later. I guess you have encountered a build issue with Python-3.5? If for some reason we cannot build binary packages for Python-3.5 then maybe it is best to not support Python-3.5 and remove that version from the ```setup.py``` file. This way we don't have to explain in the ```README.md``` that for Python-3.5 users have to build from source using a C++ compiler.

How will we release a new version? It seems logical to upload binary packages to test.pypi.org after each commit. And once we have implemented all features for the next release we would manually transfer the latest version from test.pypi.org to the real pypi.org. Unfortunately I have not found a release button on test.pypi.org yet for transferring the latest files to pypi.org... Do you have an idea how we can transfer the files from test.pypi.org to pypi.org?

**Comment by brl0** [comment]
> source archive is missing

Added a separate job to the pipeline to upload source archive.

> I guess you have encountered a build issue with Python-3.5

You guess correctly.  The problem was only with the Windows build.  I was able to get it working by using a different vmImage.

> transfer the files from test.pypi.org to pypi.org

I was using TestPyPI just to ensure that things were working correctly.  Now that everything is working, we can configure the Azure pipeline to upload directly to PyPI, rather than TestPyPI.

> How will we release a new version?

The first real line of the Azure pipeline is the [trigger](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml).  I think we only want this pipeline triggered on new releases since this pipeline is primarily meant to be a delivery pipeline.

I am not sure what the best way to structure the testing pipeline.  You still have Travis CI configured on this project, so perhaps no changes are really necessary.  I believe that is triggered for all PRs, and hopefully also for any changes.  What are your thoughts?

I will change the trigger to releases only when I make the change to upload to the real PyPI.
Let me know if you are ready for me to make that change.

**Comment by kimwalisch** [comment]
> I am not sure what the best way to structure the testing pipeline. You still have Travis CI configured on this project, so perhaps no changes are really necessary. I believe that is triggered for all PRs, and hopefully also for any changes. What are your thoughts?

For now, we should leave travis and appveyor testing as is. It works reliably so no need to change it.

> The first real line of the Azure pipeline is the trigger. I think we only want this pipeline triggered on new releases since this pipeline is primarily meant to be a delivery pipeline.

Ideally every commit should run the pipeline and upload to test.pypi.org. And when we finally do the release (tag the release in git) the pipeline should run and also upload to the real pypi.org. The reason why I would prefer such a scheme is that in my experience uploading to pypi.org (and test.pypi.org) often fails because of some issues. Then you have to fix the issues and upload again. Ideally I would like to avoid these issues and be sure that when we do a new release that it will also upload successfully to pypi.org.

We could always upload the build artifacts to test.pypi.org. Since we are currently using tags only for releases we can conditionally upload the build artifacts to pypi.org when a new tag has been created.

```yml
jobs:
- job: upload_pypi
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  steps:
    - script: echo "Upload to pypi.org."
```

* https://medium.com/faun/azure-pipelines-and-git-tag-quirks-1daaba61713a
* https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml

**Comment by kimwalisch** [comment]
The code below is only triggered for new releases, I have not tested it though...

```bash
- script: # Command to upload to pypi.org
  condition: startsWith(variables['build.sourceBranch'], 'refs/head/release/')
```

* https://stackoverflow.com/a/53328976

**Comment by brl0** [comment]
To summarize:
For releases: build, upload to TestPyPI, if successful upload to PyPI.
Commits on master: build and upload to TestPyPI.

What about PRs or commits to other branches?  Do you want those to trigger build and upload to TestPyPI?

**Comment by kimwalisch** [comment]
> What about PRs or commits to other branches? Do you want those to trigger build and upload to TestPyPI?

Commits to other branches should not be uploaded to test.pypi.org. I don't think we need to upload PRs to test.pypi.org either because the merge into the master branch should trigger an upload to test.pypi.org.

**Comment by brl0** [comment]
I think I have it configured the way you want.
Triggers on master and releases.  I excluded README.md from the triggers.
Upload to PyPI is conditional on being a release.

I restructured to combine the two separate jobs I had created into one, using variables to handle the differences.

I added the script to upload to the real PyPI, but it will not work until we add a variable `pypi_token` containing a token generated from PyPI.

Do you want the token generated under my PyPI account or yours.  I don't think it would matter unless there is some sort of upload tracking by author.  

Let me know if you have any other thoughts, questions, or concerns.

**Comment by kimwalisch** [comment]
> Do you want the token generated under my PyPI account or yours. I don't think it would matter unless there is some sort of upload tracking by author.

Go ahead and create it under your account.

> Let me know if you have any other thoughts, questions, or concerns.

```yml
  - script: |
      cd lib
      git clone https://github.com/kimwalisch/primesieve.git
      cd primesieve
      git checkout v7.4
      cd ../..
    displayName: 'Git primesieve lib'
```

I think we can improve this to:

```yml
  - script: |
      git submodule update --init
    displayName: 'Git primesieve lib'
```

**Comment by brl0** [comment]
Change made, although I am not sure what version of the lib that will use.

**Comment by brl0** [comment]
I ran a quick check for myself and it indeed checked out the correct version.  Thanks for the tip.

**Comment by brl0** [comment]
I added the PyPI token to the Azure pipeline.  Now if you tag a release, it should upload to the real PyPI.
I am not really sure how to test without making a release.

**Comment by kimwalisch** [comment]
I have released primesieve-python 2.0.1 (tag v2.0.1) however the Azure pipeline has not run. The current release trigger does not seem to work...

If the release trigger does not work we will probably need to switch to the tags trigger and the code below:

```
jobs:
- job: upload_pypi
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  steps:
    - script: echo "Upload to pypi.org."
```

@brl0: What's your opinion on this?

**Comment by brl0** [comment]
It looked like the pipeline ran, but the condition I was using did not trigger properly.

I placed the condition you suggested into the pipeline to see if that triggers the upload.  There is no need to make a separate job, we just need to modify the condition for the PyPI upload script.

Can you try it again?

**Comment by kimwalisch** [comment]
I have done a new release but it looks like the pipline has not run. So I think we need to change the trigger as well...

**Comment by brl0** [comment]
It looks like the pipeline ran, so the trigger is working properly.  In fact, it ran twice in the last hour, once for update to version 2.02, and once for update to changelog.

The problem is the condition for the upload script is not being met, as can be seen [here](https://dev.azure.com/kimwalisch/primesieve-python/_build/results?buildId=16&view=logs&j=112b7a9f-b575-5dbc-614a-bf2981e55f8b&t=d855030b-9c39-515c-c296-1f425a55fd4e&l=3).

I'll dig in some more, and I'll try to test from my fork so we don't need to keep incrementing the version needlessly.

**Comment by kimwalisch** [comment]
> The problem is the condition for the upload script is not being met, as can be seen here.

```
Expanded: startsWith('refs/heads/master', 'refs/tags/')
```

So it ran because of a commit on the master branch but not because I tagged the release. Try to add the tag trigger and remove the release trigger...

**Comment by brl0** [comment]
Here is what I came up with... it works, but I suspect there may be a better way.

I set the pipeline to trigger only for tags containing v*, and removed the condition from PyPI upload.  So anytime this pipeline is run, which will only be for a tagged release or manually, it will try to upload to PyPI.  If it was triggered manually, but had previously been run successfully, no harm will be done because twine will skip existing files.

A second pipeline will be created that triggers on changes to master, but excludes tagged releases to avoid unnecessary work.  This will not upload to PyPI, only to TestPyPI.

This is just the best working approach I have come up with so far.  I welcome improvements, and I will update if I come across a better way.

**Comment by brl0** [comment]
[Here](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) are the predefined variables that can be used for conditions.

**Comment by kimwalisch** [comment]
> This is just the best working approach I have come up with so far.

It's good, I like it :-) I have just renamed the 2 azure files to ```azure-pipelines-release.yml``` and ```azure-pipelines.yml```.

While doing a few more random checks before trying to do the next release, I found that the latest upload to test.pypi.org was from yesterday even though I did a few changes today. Could this be caused by the code below?

```yml
  - script: |
      python -m twine upload --skip-existing ...
```

Shouldn't we always overwrite the latest version on test.pypi.org? Otherwise if we install primesieve-python from test.pypi.org (for testing) we might install an older version than we would expect.

**Comment by brl0** [comment]
Unfortunately without that flag it would just throw an error if the file already exists.  
From the doc for that feature:
> Continue uploading files if one already exists. (Only
                        valid when uploading to PyPI. Other implementations
                        may not support this.)

Once your comfortable with everything and ready to upload to PyPI, you can either manually trigger the release pipeline, or update the version to trigger the release pipeline.

**Comment by kimwalisch** [comment]
I have done a new release but unfortunately none of the pipelines has run. Do you have an idea what went wrong? (Travis was run correctly after this release) 

> Unfortunately without that flag it would just throw an error if the file already exists.

OK, not a big issue. We can increase the version in setup.py shortly before the release and if the upload to test.pypi.org works correctly, then we do the actual release.

**Comment by brl0** [comment]
I will look into it.

**Comment by kimwalisch** [comment]
You can do new releases as well, there is not other way to test it.

For a new release you need to:

* Update version in setup.py
* Update ChangeLog
* Create a new release here: https://github.com/kimwalisch/primesieve-python/releases

**Comment by brl0** [comment]
The pipeline did run, but I think I had them switched around or something.  
I also forgot to add the token for PyPI, so it would not have been able to upload even if the correct pipeline had run.
I added the token, and renamed the yml files and the pipelines in Azure to make it more clear.  After renaming, the pipeline settings have to be changed to point to the new file name.
I will test the release pipeline, first by manually triggering the pipeline in Azure, and then by creating a new release to make sure that process works properly.

**Comment by brl0** [comment]
> We can increase the version in setup.py shortly before the release and if the upload to test.pypi.org works correctly, then we do the actual release.

The release pipeline first attempts to upload to TestPyPI, and will only upload to the real PyPI if no error occurs.
Basically, in order for a PyPI upload to be performed, the package must build without error, install correctly, pass all tests, and upload to TestPyPI without error.  All of this is done in the release pipeline.
The testing pipeline will run automatically for any commits to master, so as long as the most recent commits have passed successfully, you are good to go if you want to make a release.

**Comment by brl0** [comment]
I think we are in good shape.  v2.0.3 is now available via PyPI.
It looks like you are about to make a 2.0.4 release, so hopefully that will properly trigger the release pipeline.

**Comment by kimwalisch** [comment]
Yes, I wait for the azure pipelines to finish testing the last commits. After that I will do the release.

**Comment by brl0** [comment]
I wonder if I should have the pipelines actually install the packages from TestPyPI after the upload?  That would confirm the validity of the actual packages.  What do you think?

**Comment by kimwalisch** [comment]
> I wonder if I should have the pipelines actually install the packages from TestPyPI after the upload? That would confirm the validity of the actual packages. What do you think?

Yes, that would make sense if it is not to complicated to add that test.

**Comment by brl0** [comment]
Both pipelines now attempt to install packages after uploads.

**Comment by brl0** [comment]
DOH!  I just noticed that that conda feedstock does not cover python 3.5.

**Comment by brl0** [comment]
I think I finally managed to fix the conda-forge feedstock.

**Comment by kimwalisch** [comment]
I have done a new release and the upload to pypi.org has worked this time!

However while testing afterwards I have found that the Windows wheels do not work. They install without issues, but when trying to use primesieve I get an error (at the end of the log I reinstall the primesieve-2.0.0 wheel which works fine):

```
> pip3 install primesieve
Collecting primesieve
  Using cached https://files.pythonhosted.org/packages/8b/fe/d1d87c51c071e899115b02c5afae931c7c9a85e4dda404ca4dd67b5083e5/primesieve-2.0.5-cp37-cp37m-win_amd64.whl
Installing collected packages: primesieve
Successfully installed primesieve-2.0.5

> python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from primesieve import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\primesieve\__init__.py", line 1, in <module>
    from primesieve._primesieve import *
ImportError: DLL load failed: The specified module could not be found.
>>> exit()

> python -m pip uninstall primesieve
Uninstalling primesieve-2.0.5:
  Would remove:
    c:\program files\python37\lib\site-packages\primesieve-2.0.5.dist-info\*
    c:\program files\python37\lib\site-packages\primesieve\*
Proceed (y/n)? y
  Successfully uninstalled primesieve-2.0.5

> pip3 install "primesieve<=2.0.0"
Collecting primesieve<=2.0.0
  Using cached https://files.pythonhosted.org/packages/fc/e3/8d3093fc9f5a20f0a592d556e9e6028fd5f9e64e84e2698bd2eb3817af78/primesieve-2.0.0-cp37-cp37m-win_amd64.whl
Installing collected packages: primesieve
Successfully installed primesieve-2.0.0

> python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from primesieve import *
>>> primes(10)
array('Q', [2, 3, 5, 7])
>>>
```

I have checked the content of the primesieve directory after the installation and the directories of both versions (2.0.0 and 2.0.5) contain the same files. However the size of the files is slightly different:

```
 Directory of C:\Users\kim\Desktop\primesieve-2.0.0

19/12/2019  10:13    <DIR>          .
19/12/2019  10:13    <DIR>          ..
19/12/2019  10:13    <DIR>          numpy
19/12/2019  10:13           208.384 _primesieve.cp37-win_amd64.pyd
19/12/2019  10:13                37 __init__.py
19/12/2019  10:13    <DIR>          __pycache__
               2 File(s)        208.421 bytes
               4 Dir(s)  63.386.779.648 bytes free

C:\Users\kim\Desktop>dir primesieve-2.0.5
 Volume in drive C is System
 Volume Serial Number is CE3E-CA07

 Directory of C:\Users\kim\Desktop\primesieve-2.0.5

19/12/2019  10:12    <DIR>          .
19/12/2019  10:12    <DIR>          ..
19/12/2019  10:12    <DIR>          numpy
19/12/2019  10:11           197.632 _primesieve.cp37-win_amd64.pyd
19/12/2019  10:11                38 __init__.py
19/12/2019  10:12    <DIR>          __pycache__
               2 File(s)        197.670 bytes
               4 Dir(s)  63.386.779.648 bytes free
```

So my guess is that the shared libprimesieve (DLL) we have built for primesieve-2.0.5 is not correct (also indicated by error message further up). Can you check if it works on your Windows PC?

**Comment by kimwalisch** [comment]
Normally C extensions on Windows must be built using the same compiler version that was used to build the Python compiler. For Python 3.5 and 3.6 the MSVC 2015 compiler was used and for Python 3.7 and 3.8 the MSVC 2017 compiler was used (see here https://pythondev.readthedocs.io/windows.html). From the Azure pipeline logs I see that for Python 3.7 we are currently building the wheels using MSVC 2019, this might be an explanation why it does not always work.

**Comment by brl0** [comment]
Just when I thought we had it...

I am changing the image that the windows versions are built on, and trying to add this sort of simple test to confirm that the package actually works after install.

On the bright side, I've really been learning a lot.  :)

**Comment by kimwalisch** [comment]
> Just when I thought we had it...

Yes, I am now also realising the task is much harder than I thought it would be. After reading the https://iscinumpy.gitlab.io/post/azure-devops-python-wheels blog post and searching for online other people's code to build Windows wheels I actually think you chose the right image ('vs2017-win2016').

The blog post mentions that for C++11:

> Let's show what it would look like if you need a more powerful compiler, such as MSVC 2017. Note: Do not do this unless you need C++11+! It will force your users to have the MSVC 2015+ redistributable to run, instead of the “normal” 2008 redistributable that Python requires.

And then it shows the 2 scripts ```.ci/azure-setup.yml``` and ```.ci/azure-steps.yml```. libprimesieve requires C++11 so maybe we need this as well?

**Comment by brl0** [comment]
I can reproduce the issue consistently in a fork of the pipeline, I just don't know how to solve the issue.  The problem is consistent across all platforms we're building on, so I don't think it is the compiler.

When I tried reproducing on my system, I did not have the issue, instead it worked correctly.

Any ideas on what the problem might be?

**Comment by kimwalisch** [comment]
> Any ideas on what the problem might be?

Does the issue exist for both 32-bit (x64) and 64-bit (x64)? I have tested only 64-bit.

The only difference that I could find is that other people have set the architecture e.g.:

```
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: '$(python.architecture)'
````

And also here https://github.com/pygae/clifford/blob/master/azure-pipelines.yml#L177.

**Comment by kimwalisch** [comment]
> When I tried reproducing on my system, I did not have the issue, instead it worked correctly.

Maybe we should try to understand under what circumstances it works or does not work. Is the issue present for all Python versions? What operating system do you use? What operating system is used for azure pipelines...

**Comment by brl0** [comment]
I am on Windows 10, I think the environment it worked in was Py37.
The Azure Windows image we are using is on Windows Server 2016.  But I am also seeing this problem happen on the Linux and Mac builds.  In the pipelines, all versions fail in the exact same way, an error about cannot find primesieve._primesieve.  
I have the feeling this is something silly I am missing or overlooking.  I'll keep digging into it.

**Comment by kimwalisch** [comment]
> In the pipelines, all versions fail in the exact same way, an error about cannot find primesieve._primesieve.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/runner/runners/2.163.1/work/1/s/primesieve/__init__.py", line 1, in <module>
    from primesieve._primesieve import *
ImportError: No module named 'primesieve._primesieve'
```

I have seen this issue many times before. I don't think this is a new issue but unfortunately I have not been able so far to understand when this issue happens.

> I have the feeling this is something silly I am missing or overlooking. I'll keep digging into it.

I don't think this issue is easy to solve and I think it will require a lot of work to make it work reliably across all operating systems. For this reason I think it is best to revert to primesieve-python-2.0.0 and move the current master branch to a development branch. I will do that.

While reading the documentation of cibuildwheel I realised that what we are currently doing using azure Pipelines is dead simple using travis (build wheels, upload using twine upon new release), see here: https://github.com/joerick/cibuildwheel#example-setup. So maybe we should try building wheels using travis and see if these wheels work more reliably. I think this new test will take far less time than fixing the issues we currently have with Azure Pipelines.

**Comment by kimwalisch** [comment]
**Good news:** I have built Windows wheels using travis that work on my PC!

The code is on the ```travis-upload-pypi``` branch. All new code is in the ```.travis.yml``` file and that file uploads to both test.pypi.org and pypi.org (that works already). Currently only wheels for Python 3.7 are built (for Windows, macOS and Linux, both 32-bit and 64-bit).

Here is what still needs to be done:

* Test on Linux and macOS
* Add support for Python 3.5, 3.6 and 3.8 (currently only wheels for Python 3.7 are built)
* Also upload source code archive (currently only wheels are uploaded)

Can you help with that? I really hope we are lucky and the wheels work on Linux and macOS... So far travis has been much easier to set up than Azure pipelines with its crazy permission management. I really hope we can get wheels working with travis and then ditch Azure pipelines which has caused so many issues thus far.

**Comment by brl0** [comment]
Another mystery... 
CIBuildWheel has an option to run test commands after build for which it automatically installs the built wheel.  I included pytest and `from primesieve import primes; primes(10)` and both commands succeed with expected output, on all platforms and versions.
But if I then try to reinstall from TestPyPI, the test fails with the `primesieve._primesieve` error.
This seems like a strange way to be failing.

**Comment by kimwalisch** [comment]
The wheels are finally working!

This morning I was on the verge of giving up because the macOS wheels failed to be uploaded to pypi. But then I realized that somehow Python 2.7 was used on macOS even though I had specified that Python 3.x should be used. This is when I discovered that the macOS version supported by travis does not support Python 3.x out of the box.

The task of building wheels is so complicated mainly because of the minor differences of the different operating systems and tool chains e.g. travis supports Python 3.x for Linux only, for macOS and Windows you have to install Python 3.x manually yourself. It is not possible to know about these issues upfront, you learn about them the hard way when your build fails.

I have tested the new primesieve wheels on Windows, macOS and Linux and the wheels worked fine for me. I don't know why the wheels built with Azure pipelines did not work reliably because in Travis I also built the wheels using cibuildwheel. But it works now and it does not matter anymore why it did not work with Azure pipelines and as I have mentioned before Azure pipelines is difficult to set up so I am happy that we don't need it anymore.

**Comment by brl0** [comment]
That's great!  

I am still very interested in understanding the problem with the other wheels.  I inspected them directly, and they contained the necessary files.  The puzzling thing is that they would still work sometimes.  I am not as concerned about the pipelines as I am about why the wheels that looked ok didn't always work correctly.

I am very glad that you were able to get something working.  I'll circle back around to check that the conda build is up to date and covering all versions and systems correctly.

**Comment by brl0** [comment]
Did you do anything to purge our test packages from TestPyPI, or did that happen through some automated process?  Just curious, I've been wondering about how to clean those up.

**Comment by brl0** [comment]
I hate to say it, but I still seem to be having the same trouble with version 2.1.0.  Although for now I am just testing from Azure.  I really wonder if we are dealing with a bug in the wheel installer, because it is not always copying the files that are in the wheel package.

**Comment by kimwalisch** [comment]
> Did you do anything to purge our test packages from TestPyPI, or did that happen through some automated process? Just curious, I've been wondering about how to clean those up.

I have removed these releases manually on the test.pypi and pypi websites because I realized (by looking at ```--verbose``` output) that when you install the primesieve package pip iterates over all releases and installs the last version that works. So when there are fewer releases this should theoretically speedup the installation process (and we had made many new releases with lots of wheels over the past few days).

> I hate to say it, but I still seem to be having the same trouble with version 2.1.0. Although for now I am just testing from Azure. I really wonder if we are dealing with a bug in the wheel installer, because it is not always copying the files that are in the wheel package.

The cibuildwheel has integrated support for testing built wheels, so after the wheel has been built it will spin up a new docker container and install the wheel into it, then it will run the tests. I have implemented this in travis.yml and all tests pass successfully on Windows, macOS and Linux.

Here is the code to enable testing with cibuildwheel:

```bash
export CIBW_TEST_REQUIRES="pytest numpy"
export CIBW_TEST_COMMAND="pytest {project}"
```

As mentioned before I have also tested installing primesieve on Windows, macOS and Linux on my own PCs and it worked fine. I have also installed primesieve on https://repl.it/languages/python3 (Linux/x64) and that also worked. Using the wheels from Azure pipelines did not work for me. So it seems to me that the new travis wheels are OK.

Could you please try installing the new wheels on your own PC and report if they work?

**Comment by brl0** [comment]
The wheels always worked on my PC, which is why I am so stumped by this issue.
I found an [issue](https://github.com/pypa/pip/issues/4959) that looks like it might be the same.  We may just need to create a manifest file for the install.  
The wheels were passing the same cibuildwheel tests on Azure.  What did not work is to test them after installing directly in the current environment.
I'll keep digging to get a better handle on this.  The old and new wheels contained the correct files, and they would be listed if you run `pip show --files primesieve`, but the binary `.so` and `.pyd` files would not get copied for some reason.

**Comment by brl0** [comment]
Here are the environment variables I was using for cibuildwheel, just in case they may be helpful for you:

    CIBW_BUILD_VERBOSITY: 3
    CIBW_BEFORE_BUILD: python -m pip install -U pip setuptools wheel Cython numpy
    CIBW_TEST_REQUIRES: pytest
    CIBW_TEST_COMMAND: pytest {project}/tests && python -c "from primesieve import primes;print(primes(10))"

**Comment by brl0** [comment]
I finally got to the bottom of the ImportError issue I have been experiencing, see [here](https://github.com/pypa/pip/issues/7507) if you are interested.
Basically trying to test directly from the repo directory was importing from the repo rather than from the installed package.  So not really a problem with the install, just minor user error.  I feel much better about the entire process now that I understand what the problem was.

Let me know what I can do to assist in moving things forward.

**Comment by brl0** [comment]
I think I don't have rights to clean up TestPyPI, I had uploaded a couple test releases as I was troubleshooting.

**Comment by kimwalisch** [comment]
> I think I don't have rights to clean up TestPyPI

I have now made you an owner (like myself) of the primesieve project on both test.pypi and pypi. Please enable 2-factor authentication on both test.pypi and pypi if you have not done it yet, this will reduce the risk of the primesieve pypi project getting hacked.

> I had uploaded a couple test releases as I was troubleshooting.

After thinking about it I don't think it is necessary to delete releases from test.pypi because it is used just for testing. We can always increase the minor version when we do the next real release. So the next release number would be primesieve-2.2.0.

> Basically trying to test directly from the repo directory was importing from the repo rather than from the installed package. So not really a problem with the install, just minor user error. I feel much better about the entire process now that I understand what the problem was.

Great!

> Let me know what I can do to assist in moving things forward.

With all the work we have done over the last few weeks primesieve-python is in excellent shape now: it runs much faster than before, we provide binary wheels for pypi and releasing a new version is dead simple now thanks to improved travis-ci.  For me personally primesieve-python is now feature complete and we just need to maintain it over time e.g. if a new python version comes out we need to make a new release. Also we might need to support more CPU types (e.g. ARM64) on pypi in the coming years if e.g. Apple suddenly decides to switch all their PCs from x64 to ARM64.

I plan to do a new release of primesieve C++ library on the weekend. After that we should wait for at least a week to see if any users report any issues. If not we can update primesieve-python to the latest libprimesieve and do a new release, this should be dead simple now thanks to the work we have done. I would be happy if would do the next primesieve-python release.

Happy Christmas to you and your family!

**Comment by brl0** [comment]
> I have now made you an owner

Thanks for your confidence, I honestly feel honored.

> Please enable 2-factor authentication

Agreed and already done on sign up.

> thanks to improved travis-ci

cibuildwheel is a great tool and made the build process much easier.  

> primesieve-python is now feature complete

Agreed, my initial goal was actually just to update to the latest version of the library, but working through these various issues has been a great learning opportunity and experience.

> I plan to do a new release of primesieve C++ library 

I'd be happy to update and release primesieve-python once we are confident the new version is stable.

I was also thinking it would be good to update the [primesieve-feedstock](https://github.com/conda-forge/primesieve-feedstock) for conda-forge.  That is the feedstock for the primesieve binaries that are separately installable from the python bindings.  That feedstock is still on version 5.7.3.

> Happy Christmas to you and your family!

And a very Merry Christmas to you and yours!

**Comment by kimwalisch** [comment]
> I was also thinking it would be good to update the primesieve-feedstock for conda-forge. That is the feedstock for the primesieve binaries that are separately installable from the python bindings. That feedstock is still on version 5.7.3.

I think that nobody uses this and there is no need for us to maintain unneeded projects. Personally I would prefer if we would close/remove this project. This also reduces confusing about which primesieve to install with conda.

Ideally I would close/remove the primesieve project and afterwards rename the python-primesieve project to primesieve so that users can install the primesieve python library using ```conda install primesieve``` similarly like using pip.

However when we do this we probably break other people's build. What is your opinion on this? It seems like conda is only used for Python so there is no need to maintain a C++ library on it: https://news.ycombinator.com/item?id=15567223

**Comment by brl0** [comment]
I think your plan is good and very reasonable.  

Just an idea, but perhaps before doing so we could add a primesieve CLI to the python bindings, which might make the transition nearly transparent if anyone was relying on the C++ CLI.

**Comment by kimwalisch** [comment]
> Just an idea, but perhaps before doing so we could add a primesieve CLI to the python bindings, which might make the transition nearly transparent if anyone was relying on the C++ CLI.

By primesieve CLI you mean the primesieve command-line program, right? I don't think this is needed, personally I think that users that install primesieve using pip or conda want to use the primesieve python library and not the primesieve command-line program. If they want to install the primesieve command-line program they should install it using the operating system's official package manager.

I think our main concern should be that if we rename python-primesieve-feedstock to primesieve-feedstock then we will break the build of all people that have installed primesieve using ```conda install python-primesieve```. I usually try to avoid backwards incompatible changes but here I am strongly in favour of doing it as I think there are currently very few users of  python-primesieve-feedstock.

However we don't seem to have rights to simply delete or rename python-primesieve-feedstock so we will have to ask the project owner (or a conda-forge administrator) if they are OK with our plan to rename python-primesieve-feedstock to primesieve-feedstock.
